#paths_to_2d_data = ['/media/minyoungpark/T7 Touch/pop_1103/iteration-19/cam_0_interp.csv',
#'/media/minyoungpark/T7 Touch/pop_1103/iteration-19/cam_1_interp.csv',
#'/media/minyoungpark/T7 Touch/pop_1103/iteration-19/cam_2_interp.csv',
#'/media/minyoungpark/T7 Touch/pop_1103/iteration-19/cam_3_interp.csv']

paths_to_2d_data = ['F:/pop_1103/iteration-19/cam_0_interp.csv',
'F:/pop_1103/iteration-19/cam_1_interp.csv',
'F:/pop_1103/iteration-19/cam_2_interp.csv',
'F:/pop_1103/iteration-19/cam_3_interp.csv']

#output_video_path = '/media/minyoungpark/New Volume/pop_1103/iteration-19/'
output_video_path = 'F:/pop_1103/iteration-19/'

[video]
fps = 30
resolution = [2048, 1536]

[calibration]
# checkerboard / charuco / aruco
board_type = 'charuco'

# width and height of grid
board_size = [5, 7]

# number of bits in the markers, if aruco/charuco
board_marker_bits = 6

# number of markers in dictionary, if aruco/charuco
board_marker_dict_number = 50

# length of marker side
board_marker_length = 23.2 # mm

# If aruco, length of marker separation
# board_marker_separation_length = 1 # mm

# If charuco or checkerboard, square side length
board_square_side_length = 38.6 # mm

#calib_video_path = '/media/minyoungpark/T7 Touch/calib_1103/'
calib_video_path = 'F:/calib_1103/'
calib_video_prefix = 'cam'
video_extension = 'avi'


[triangulation]
cam_align = "0"
reconstruction_threshold = 0.3
#reconstruction_output_path = '/media/minyoungpark/T7 Touch/pop_1103/iteration-19'
reconstruction_output_path = 'F:/pop_1103/iteration-19'


[labeling]
scheme = [
  ["Wrist", "CMC_thumb"],
  ["CMC_thumb", "MCP_thumb"],
  ["MCP_thumb", "IP_thumb"],
  ["IP_thumb", "Tip_thumb"],
  ["Wrist", "MCP1"],
  ["Wrist", "MCP2"],
  ["Wrist", "MCP3"],
  ["Wrist", "MCP4"],
  ["MCP1", "PIP1"],
  ["MCP2", "PIP2"],
  ["MCP3", "PIP3"],
  ["MCP4", "PIP4"],
  ["PIP1", "Dip1"],
  ["PIP2", "Dip2"],
  ["PIP3", "Dip3"],
  ["PIP4", "Dip4"],
  ["Dip1", "Tip1"],
  ["Dip2", "Tip2"],
  ["Dip3", "Tip3"],
  ["Dip4", "Tip4"]]

bodyparts_interested = ['Wrist', 'CMC_thumb', 'MCP_thumb', 'MCP1', 'MCP2', 'MCP3', 'MCP4',
          'IP_thumb', 'PIP1', 'PIP2', 'PIP3', 'PIP4', 'Dip1', 'Dip2', 'Dip3', 'Dip4',
          'Tip_thumb', 'Tip1', 'Tip2', 'Tip3', 'Tip4']
